apiVersion: "scaling.com/v1"
kind: AutoscalingDefinition
metadata:
  name: image-service-autoscaling-definition
spec:
  scaleTarget:
    matchNamespace: "default"
    labelName: "app.kubernetes.io/name"
    matchLabel: "image-service"
    targetType: "deployment"
  minReplicas: 1
  maxReplicas: 5
  intervalBetweenAutoscaling: "2m"
  scalingStep: 1
  metrics:
    - name: "cpu"
      metricType: "prometheus"
      prometheusPath: "http://prometheus:9090"
      prometheusQuery: "rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"image-service\"}[2m])"
      scaleDownValue: "0.33"
      scaleUpValue: "0.74"
      scaleValueType: "double"
      numOfTests: 3
      algorithm: "arimax"
      trimmedPercentage: 10
      scrapeInterval: "1s"
      testInterval: "1m"
      autoregresionDegree: 2
      autoregressionCoefficients: ["1", "-1"]
      movingAverageDegree: 1
      movingAverageCoefficients: ["2"]
      exogenousRegressorQuery: "increase(http_server_requests_seconds_count{namespace=\"default\", container=\"image-service\", uri=\"/noauth/images/top20\"}[2s])"
      exogenousRegressorCoefficient: "0.5"
      exogenousRegressorMaxValue: "30.0"

